name: Publish Static Web App to Azure Blob Storage

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

#     - name: Login to Azure
#       uses: Azure/login@v1
#       with:
#         creds: ${{secrets.AZURE_CREDENTIALS }}

#     - name: Install npm packages
#       shell: bash
#       run: |
#         cd $GITHUB_WORKSPACE
#         npm install
#     - name: Build app
#       shell: bash
#       run: |
#         cd $GITHUB_WORKSPACE
#         npm run build
#     - name: Test app
#       shell: bash
#       run: |
#         cd $GITHUB_WORKSPACE
#         npm run test:unit

#Steve's version: do all the above on your local workspace, then...
#Bulk upload the contents of /dist in the root folder to the blob.

    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
#          az storage blob upload-batch -s $GITHUB_WORKSPACE/dist -d \$web --connection-string "${{secrets.AZURE_STORAGE_CONNECTION_STRING}}"
